# Your workflow name.
name: Build & Deploy

# Run on push to any branch.
on:
  push

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release
      # - name: Test
        # run: dotnet test -c Release --no-build
      - name: Publish
        run: dotnet publish -c Release -o app/publish
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: app/publish
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Deploy only on the master branch.
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: StadtLandFussApi/app/publish
      - name: Deploy to Heroku with Docker
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}
          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          # Dockerfile directory.
          dockerfile_directory: StadtLandFussApi/
          # Dockerfile name.
          dockerfile_name: Dockerfile
          # Additional options of docker build command.
          docker_options: "--no-cache"
          # For more information look at https://devcenter.heroku.com/articles/process-model
          process_type: web
